---
  language: go
  sudo: false
  notifications:
    email: true
  go:
    - stable
    - tip
  env:
    global:
      - GO15VENDOREXPERIMENT=1
  matrix:
    allow_failures:
      - go: tip
    fast_finish: true
  install:
    - go get github.com/golang/lint/golint
    - go get honnef.co/go/tools/cmd/staticcheck
  script:
    - go build -v
    - go vet $(go list ./... | grep -v vendor)
    - staticcheck $(go list ./... | grep -v vendor)
    - test -z "$(golint ./... | grep -v vendor | tee /dev/stderr)"
    - test -z "$(gofmt -s -l . | grep -v vendor | tee /dev/stderr)"
    - go test $(go list ./... | grep -v vendor)
    - make release
  deploy:
    provider: releases
    api_key:
      secure: "UgvN6AVvuIUHBwTQqS1m7Dn0e0yHQSQYFlZUrjbuRCc+cVNwF2K7mHwh3xaYcF/eyHc8MtHL91DTF1D9XhdR2XjyQbFtYOHxcG4ToTvpku4V9JF6JQg0SfDs2A5frHuV3dUKQXzZpusY36AkQ3ES3CFErwQBGAbScJSjKMsyBBPkI1jdpZhChiUJxi36NE6CZiiq6ij76Ho4cFlMlAOWCCcncprvULFMD9g6C4jEKyclwlcYCjCvOKpmtZMlJfMjKYw6gsKyuyRWeKSIa1goHlXdcgStW02kkBZVowJkig0UhThSf1fh8aFLovR1VaoiDzg+RsmaZc+3QpDV0KCyiW/uKAJ5CeNBy4lubnWJQmkKP1pmLv2LmqQ5Au4TazG7lMhK26eLu/vx2VL52k5aO30FZE7sbb9zbd2LtsuJWjZvLxm3pA6iLTF1qoS3To/Wq4VZiRsvx8bkZ3YbvNIA2IpiilN2OWi7XIz5ZaKW4MEUrj7mzKB1lIgTczz+JbiYxnu2uNCSRfrjCVLYiARI+K/Qa0ckiSqGq8pEpbxPujUS06IK1vghv1iO1nQl6VEqvMmLkNjZZAWgiuJ9oJ4qref86w55uddqeMzfK0LDrlR5OuAa6lgrOaRWFGlBvKJY0Z1B6/tg2sMOYlWkH5bvJMgD741zyBWJ6WlbENSIh0Q="
    file:
      - cross/contained.af-linux-amd64.md5
      - cross/contained.af-linux-amd64.sha256
      - cross/contained.af-linux-amd64
    skip_cleanup: true
    on:
      go: stable
      tags: true
